export const PERSIST_TASK = 'PERSIST_TASK'
export const PERSIST_TASK_IN_PROGRESS = 'PERSIST_TASK_IN_PROGRESS'
export const PERSIST_TASK_SUCCESS = 'PERSIST_TASK_SUCCESS'
export const PERSIST_TASK_ERROR = 'PERSIST_TASK_ERROR'